Algoritmo "idade"

Var

   nome1, nome2 : caractere
   idade1, idade2 : inteiro
   mediaMariaJoao : real

Inicio

  escreval("Dados da primeira pessoa: ")
  escreva("Nome: ")
  leia(nome1)
  escreva("Idade: ")
  leia(idade1)
  escreval("Dados da segunda pessoa:")
  escreva("Nome: ")
  leia(nome2)
  escreva("Idade: ")
  leia(idade2)
  
  mediaMariaJoao <- (idade1 + idade2) / 2
  
  escreval("A idade média de ", nome1, " e ", nome1, " é de ", mediaMariaJoao, " anos")

Fimalgoritmo